### ISSUE TITLE
stof100() vs int(parseFloat(x) * 100)

### ISSUE THREAD

**Issue by reki2000** [reki2000/langs-bench-dijkstra#18]
Pointed by PR #14 

`stof100` was introduced to handle floating point errors such as:
```
julia> Int32(floor(parse(Float32,"0.009")*10000))
89  # expected 90
```

* the example above is from Julia, but this occurs in C++, Python. I guess this is common error when using "float32" type. (IEEE 754 binary32)

But in this benchmark, the multiplier is 1000 and it doesn't make any error in all cases between 0.001 and 0.999
```
julia> Int32(floor(parse(Float32,"0.009")*1000))
9 
```

So we can remove stof100() and use float32 * 1000 / 10 to get x100 multiplied value for distances faster than using `stof100()`, especially in JIT style languages.

The question Is whether it is good or not to do so while taking such risk of the error.

**Comment by tatsuya6502** [comment]
How about keep using `stof100()` but try to improve its performance in JIT/interpreted languages? We could get some performance boost if we use more built-in functions (which are typically pre-compiled to the machine language) rather than using tight while loops.

Here is an example. Split the input string `"0.009"` at the period, then use built-in `parse()` and `length()` functions to calculate the result.

```julia
julia> parse(Int32, "0") * 10000 + parse(Int32, "009") * 10 ^ (4 - length("009"))
90 

julia> parse(Int32, "0") *  1000 + parse(Int32, "009") * 10 ^ (3 - length("009"))
9
```

This may be slower than doing `Int32(floor(parse(Float32,"0.009")*1000))`, but will be still faster than the original and we do not have to sacrifice the correctness.

**Comment by tatsuya6502** [comment]
to: @reki2000 
cc: @kwatch 
* * *

I did a quick test. Now I am not sure what we should do.

I changed Python and Julia scripts locally as the followings:

```diff
$ git diff
diff --git a/python/src/main.py b/python/src/main.py
index dc2f31a..2f2f8f8 100644
--- a/python/src/main.py
+++ b/python/src/main.py
@@ -1,5 +1,6 @@
 import sys
 from heapq import heappush, heappop
+from decimal import Decimal
 
 class G:
        id2idx = {}
@@ -49,6 +50,22 @@ def stof100(s):
                result *= (10 ** place)
        return result
 
+def stof100b(s):
+       ds = s.split(".")
+       # Note: This will fail if s is ".5"
+       result = int(ds[0]) * 100
+       if len(ds) == 1:
+               return result
+
+       d1 = ds[1]
+       l1 = len(d1)
+       if l1 == 1:
+               result += int(d1) * 10
+       elif l1 == 2:
+               result += int(d1)
+       else:
+               result += int(d1[:2])
+       return result
 
 def load():
        sys.stdin.readline()
@@ -58,7 +75,13 @@ def load():
                # println(data)
                s = int(data[2])
                e = int(data[3])
-               d = stof100(data[5])
+
+               # d = stof100(data[5])  # ................(a)
+               # d = stof100b(data[5])  # .............. (b)
+               # d = int(Decimal(data[5]) * 100)  # .... (c)
+               # d = int(Decimal(data[5]).scaleb(2))  #  (c')
+               # d = int(float(data[5]) * 1000) // 10  # (d)
+
                if is_debug:
                        print(f"line: {line} s: {s} e: {e} D: {d}")
                add_edge(s, e, d)
diff --git a/julia/src/main.jl b/julia/src/main.jl
index cd2a5c3..e7f9584 100644
--- a/julia/src/main.jl
+++ b/julia/src/main.jl
@@ -1,5 +1,6 @@
 import Base.push!
 #using Profile
+using FixedPointDecimals  # Run this: `using Pkg; Pkg.add("FixedPointDecimals")`
 
 include("priorityqueue.jl")
 
@@ -60,6 +61,26 @@ function stof100(s::AbstractString)::Distance
     return result
 end
 
+function stof100b(s::AbstractString)::Distance
+    ds = split(s, ".")
+    result = parse(Distance, ds[1]) * 100
+    if length(ds) == 1
+        return result
+    end
+
+    d2 = ds[2]
+    l2 = length(d2)
+    if l2 == 1
+        result += parse(Distance, d2) * 10
+    elseif l2 == 2
+        result += parse(Distance, d2)
+    else
+        # result += parse(Distance, d2[1:2])  # This creates a copy of the string.
+        result += parse(Distance, SubString(d2, 1, 2))  # This only creates a view of the string.
+    end
+    return result
+end
+
 function load!(g::G, is_debug::Bool = false)
     i = 0
     for line in eachline(stdin)
@@ -71,7 +92,12 @@ function load!(g::G, is_debug::Bool = false)
         # println(data)
         s = parse(NodeId, data[3])
         e = parse(NodeId, data[4])
-        d = stof100(data[6])
+
+        # d = stof100(data[6])  # .................................................... (a)
+        # d = stof100b(data[6])  # ................................................... (b)
+        # d = Distance(parse(FixedDecimal{Distance,2}, data[6]) * 100)  # ............ (c)
+        # d = Distance(floor(Distance(floor(parse(Float32, data[6]) * 1000)) / 10))  # (d)
+
         is_debug && println("line: $(line) s: $(s) e: $(e) D: $(d)")
         add_edge!(g, s, e, d)
     end
```

As you can see, I got four different implementations for `stof100()`:

- (a) The original `stof100()`
- (b) Modified `stof100()` to use string `split()` method.
- (c) Use fixed point decimal module/package.
    - The Python script uses the decimal module in the standard library. This module is written in C.
    - The Julia script uses an external package FixedPointDecimals, which is written in Julia.
- (d) Do float32 * 1000 / 10

I manually ran the scripts with one of these lines enabled. I got an interesting results.

In Python, (d) was the fastest and (a) was the slowest.

- (d) > (c) > (b) > (a)

In Julia, (a) was the fastest; it was faster than (d).

- (a) > (d) > (b) > (c)

Note that I could not do AOT compile for Julia. By some reason, I got segfaults when compiling. So the results may vary if you do AOT compile.

Now I am not sure what we should do. I guess replacing `stof100()` is good for Python, but maybe not for other languages.

**Environment**

- Fedora 32 (Linux x86_64)
- Python 3.8.3
- Julia 1.4.2

**Comment by tatsuya6502** [comment]
I found that Julia has integer division function. 

So this

```julia
        d = Distance(floor(Distance(floor(parse(Float32, data[6]) * 1000)) / 10))  # (d)
```

can be written as

```julia
        d = Distance(div(Distance(floor(parse(Float32, data[6]) * 1000)), 10)) # (d)
```
`div()` returns a `Int64` value, so I still needed the surrounding `Distance(..)`.

I do not see performance difference between them, so (a) is still faster than (d).

- (a) > (d) > (b) > (c)

**Comment by reki2000** [comment]
@tatsuya6502 Interesting.. And a lot of a appreciate to you digging this issue so deeply!

I think it's fair to rewrite `stof100()` with (c) way only in Python, because this is Python's characteristics from the view of performance. In other words,  `You don't write your own string parser` would be general  knowledge for Python users. I will make such update for Python code.

* For this benchmark, I decided not to choose (d) way, because it's risky to having the difference of float-to-int conversion between different languages. Especially in this test, only one difference in `distance` would lead another process for shortest path finding, which have different result than original(correct) one.

Many thanks again 👍
